### ISSUE TITLE
-l libMUSCLE 

### ISSUE THREAD

**Issue by tseemann** [marbl/parsnp#57]
This fails on modern g++
```
g++-5 -O3 -m64 -fopenmp -funroll-all-loops -fomit-frame-pointer -ftree-vectorize -g -O2 -lgomp 
-lstdc++ -lpthread -std=gnu++0x 
-Wl,-rpath,/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib 
-L/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib -lMUSCLE-3.7 
-o parsnp 
parsnp-MuscleInterface.o parsnp-parsnp.o parsnp-LCB.o parsnp-LCR.o 
parsnp-TMum.o parsnp-Converter.o parsnp-iniFile.o
```
because

`-lMUSCLE-3.7` needs to come after the object files.

**Comment by treangen** [comment]
thanks Torsten, good catch

**Comment by advaitb** [comment]
Added the fix to build_parsnp_linux.sh. Should work now :)

**Comment by tseemann** [comment]
This is not a linux issue. it will still happen on MacOS if you use g++ compiler.
